### PR TITLE
Added JSON-generaton func, see ./scripts/build-dir

### PR DESCRIPTION
**Pull request by programmersRuleTheWorld**
My first time getting around to a pull req; I created something useful for myself and figured I'd share it! Enjoy!

### CODE REVIEW

**Comment by manuelpires** [comment]
Hey! Thanks for making this PR and for taking the time to improve the repo :)
I'm sorry about the delay, wanted to let you know that I'll be reviewing all of this over this weekend that I'm free 🙏

**Comment by programmersRuleTheWorld** [comment]
Thanks man, I'm really excited as this is my first PR. :)
I've actually been working on it and by this weekend, I'll have also added
recursive functionality so it can look in nested directories for generating
the traits JSON and the restrictions lists inside of them.
I hope you like it!

**Comment by manuelpires** [comment]
First of all, I'm really sorry for the time it took me to review this PR. I've been pretty busy these last couple of months and I kind of left my personal projects alone for a while.

My observations:

- The code doesn't run on M1 Mac (my case). This is because you added `node:fs` which is available starting on Node 18. Currently I'm running this on Node 14 on my M1 Mac, because the `canvas` binaries for ARM are still not available on Node > 16, so trying to run the code on my local machine on Node > 16 is impossible right now, though it is possible on Linux based systems and on Windows. So as you can see, bumping the required Node version to 18 is not acceptable at the moment.

- I could not run the project for the reasons stated above, but from the code I see that you created a new script that builds the final JSON configuration file using Javascript. Unfortunately I don't think that is necessary for this project. For the record, I consider the main functionality of the project already finished. There could be bugs to fix, or little functionalities to add, but I don't really think this is something the project needs. The main reason is that I want the project to be used by as many people as possible, so I made it in a way that the user only has to edit a simple JSON file. This new script that you've created requires more knowledge of Javascript and adds unnecessary complexity to the project in my opinion. I'd like it to be just a main script that generates metadata and images, with some extra little add-ons for more functionality (GIFs, hashes, etc). Eventually I'd like to create a front-end for the script, instead of running it with Node, but that's another story.

- I see that you added your name, your company name, and your email to the `README.md` and `build-dir.mjs`. I know that you are just starting to write PRs and being involved in open source development, so let me tell you that this is not standard practice. The idea here is that if someone makes a contribution to the project, like a commit, that person would appear under the *Contributors* section of the repository (along with me and others), and that's it. But to add all your personal information attached to a README and a script is not really necessary at all.

For all these reasons I'm not accepting the changes and closing this PR. It's great that you've made a twist to the code so it's actually more useful for you, and I think this new functionality should remain in your own fork of the project. I hope you take this words in a good way, I'm no english native speaker so sorry if some things I'm saying sound rough, that's not my intention at all. 

Lastly, I wanted to thank you for making this PR and to start contributing to open source software, I'm fairly new to this too so may we have a great path ahead, cheers :)

**Comment by programmersRuleTheWorld** [comment]
@manuelpires thank you, the functionality I have created may best be made into a separate package, and user-friendly as a no-code solution so people don't need to know how to develop in Node to use it.
I will however resubmit a PR only for issue #4 as I would still like to help contribute and it is a simple fix to index.js.
Gracias amigo

**Pull request closed without merging**
